 
services:
  app:
    # Service name derived from application
    container_name: TripCircle-container
   
    # # Build from local Dockerfile
    #build:
    #  context: .
    #  dockerfile: Dockerfile
   
    # Use the built image
    image: nisoka7/tripcircle:v2
   
    # Map container port to host port
    ports:
      - "5050:5000"
   
    # Set working directory
    working_dir: /app
 